"""Added sale_datetime

Revision ID: 6323d00c89a8
Revises: 090b8b15452d
Create Date: 2024-10-24 16:23:53.554886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6323d00c89a8'
down_revision: Union[str, None] = '090b8b15452d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_datetime')
    # ### end Alembic commands ###
