version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head &&
               python refill_db.py &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - "8000:8000"
    restart: always

volumes:
  pg_data:
